spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/autoblog
    username: autoblog
    password: autoblog
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: false
